{{- if and (eq .Values.controller.cloudProvider "vultr") .Values.vultr.apiKey (not .Values.vultr.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-autoheal.vultrSecretName" . }}
  labels:
    {{- include "cluster-autoheal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.vultr.apiKeySecretKey }}: {{ .Values.vultr.apiKey | quote }}
{{- end }}
